// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// multinomial_resampling_n_
IntegerVector multinomial_resampling_n_(const NumericVector& weights, int ndraws);
RcppExport SEXP bayeshscore_multinomial_resampling_n_(SEXP weightsSEXP, SEXP ndrawsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const NumericVector& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< int >::type ndraws(ndrawsSEXP);
    __result = Rcpp::wrap(multinomial_resampling_n_(weights, ndraws));
    return __result;
END_RCPP
}
// rmvnorm
NumericMatrix rmvnorm(int nsamples, const NumericVector& mean, const NumericMatrix& covariance);
RcppExport SEXP bayeshscore_rmvnorm(SEXP nsamplesSEXP, SEXP meanSEXP, SEXP covarianceSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type nsamples(nsamplesSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type covariance(covarianceSEXP);
    __result = Rcpp::wrap(rmvnorm(nsamples, mean, covariance));
    return __result;
END_RCPP
}
// rmvnorm_transpose
NumericMatrix rmvnorm_transpose(int nsamples, const NumericVector& mean, const NumericMatrix& covariance);
RcppExport SEXP bayeshscore_rmvnorm_transpose(SEXP nsamplesSEXP, SEXP meanSEXP, SEXP covarianceSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type nsamples(nsamplesSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type covariance(covarianceSEXP);
    __result = Rcpp::wrap(rmvnorm_transpose(nsamples, mean, covariance));
    return __result;
END_RCPP
}
// dmvnorm
NumericVector dmvnorm(const NumericMatrix& x, const NumericVector& mean, const NumericMatrix& covariance);
RcppExport SEXP bayeshscore_dmvnorm(SEXP xSEXP, SEXP meanSEXP, SEXP covarianceSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type covariance(covarianceSEXP);
    __result = Rcpp::wrap(dmvnorm(x, mean, covariance));
    return __result;
END_RCPP
}
// dmvnorm_transpose
NumericVector dmvnorm_transpose(const NumericMatrix& x, const NumericVector& mean, const NumericMatrix& covariance);
RcppExport SEXP bayeshscore_dmvnorm_transpose(SEXP xSEXP, SEXP meanSEXP, SEXP covarianceSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type covariance(covarianceSEXP);
    __result = Rcpp::wrap(dmvnorm_transpose(x, mean, covariance));
    return __result;
END_RCPP
}
// systematic_resampling_n_
IntegerVector systematic_resampling_n_(const NumericVector& weights, int ndraws, double u);
RcppExport SEXP bayeshscore_systematic_resampling_n_(SEXP weightsSEXP, SEXP ndrawsSEXP, SEXP uSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const NumericVector& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< int >::type ndraws(ndrawsSEXP);
    Rcpp::traits::input_parameter< double >::type u(uSEXP);
    __result = Rcpp::wrap(systematic_resampling_n_(weights, ndraws, u));
    return __result;
END_RCPP
}
// phi_cpp
double phi_cpp(double y, double yi, double sigma2);
RcppExport SEXP bayeshscore_phi_cpp(SEXP ySEXP, SEXP yiSEXP, SEXP sigma2SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type yi(yiSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    __result = Rcpp::wrap(phi_cpp(y, yi, sigma2));
    return __result;
END_RCPP
}
// dphi_cpp
double dphi_cpp(double y, double yi, double sigma2);
RcppExport SEXP bayeshscore_dphi_cpp(SEXP ySEXP, SEXP yiSEXP, SEXP sigma2SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type yi(yiSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    __result = Rcpp::wrap(dphi_cpp(y, yi, sigma2));
    return __result;
END_RCPP
}
// d2phi_cpp
double d2phi_cpp(double y, double yi, double sigma2);
RcppExport SEXP bayeshscore_d2phi_cpp(SEXP ySEXP, SEXP yiSEXP, SEXP sigma2SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type yi(yiSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    __result = Rcpp::wrap(d2phi_cpp(y, yi, sigma2));
    return __result;
END_RCPP
}
// get_G_RBF_cpp
NumericMatrix get_G_RBF_cpp(NumericVector x, double sigma2);
RcppExport SEXP bayeshscore_get_G_RBF_cpp(SEXP xSEXP, SEXP sigma2SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    __result = Rcpp::wrap(get_G_RBF_cpp(x, sigma2));
    return __result;
END_RCPP
}
// get_h1_RBF_cpp
NumericVector get_h1_RBF_cpp(NumericVector x, double sigma2);
RcppExport SEXP bayeshscore_get_h1_RBF_cpp(SEXP xSEXP, SEXP sigma2SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    __result = Rcpp::wrap(get_h1_RBF_cpp(x, sigma2));
    return __result;
END_RCPP
}
// get_h2_RBF_cpp
NumericVector get_h2_RBF_cpp(NumericVector x, double sigma2);
RcppExport SEXP bayeshscore_get_h2_RBF_cpp(SEXP xSEXP, SEXP sigma2SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    __result = Rcpp::wrap(get_h2_RBF_cpp(x, sigma2));
    return __result;
END_RCPP
}
// loss_d1
double loss_d1(NumericVector theta, double sigma2, NumericMatrix Gtraining, NumericVector xtraining, NumericVector xtest);
RcppExport SEXP bayeshscore_loss_d1(SEXP thetaSEXP, SEXP sigma2SEXP, SEXP GtrainingSEXP, SEXP xtrainingSEXP, SEXP xtestSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Gtraining(GtrainingSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xtraining(xtrainingSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xtest(xtestSEXP);
    __result = Rcpp::wrap(loss_d1(theta, sigma2, Gtraining, xtraining, xtest));
    return __result;
END_RCPP
}
// loss_d2
double loss_d2(NumericVector theta, double sigma2, NumericMatrix Gtraining, NumericVector xtraining, NumericVector xtest);
RcppExport SEXP bayeshscore_loss_d2(SEXP thetaSEXP, SEXP sigma2SEXP, SEXP GtrainingSEXP, SEXP xtrainingSEXP, SEXP xtestSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Gtraining(GtrainingSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xtraining(xtrainingSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xtest(xtestSEXP);
    __result = Rcpp::wrap(loss_d2(theta, sigma2, Gtraining, xtraining, xtest));
    return __result;
END_RCPP
}
// K_cpp
double K_cpp(double y, double ystar, double sigma2star);
RcppExport SEXP bayeshscore_K_cpp(SEXP ySEXP, SEXP ystarSEXP, SEXP sigma2starSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type ystar(ystarSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2star(sigma2starSEXP);
    __result = Rcpp::wrap(K_cpp(y, ystar, sigma2star));
    return __result;
END_RCPP
}
// dK_cpp
double dK_cpp(double y, double ystar, double sigma2star);
RcppExport SEXP bayeshscore_dK_cpp(SEXP ySEXP, SEXP ystarSEXP, SEXP sigma2starSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type ystar(ystarSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2star(sigma2starSEXP);
    __result = Rcpp::wrap(dK_cpp(y, ystar, sigma2star));
    return __result;
END_RCPP
}
// d2K_cpp
double d2K_cpp(double y, double ystar, double sigma2star);
RcppExport SEXP bayeshscore_d2K_cpp(SEXP ySEXP, SEXP ystarSEXP, SEXP sigma2starSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type ystar(ystarSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2star(sigma2starSEXP);
    __result = Rcpp::wrap(d2K_cpp(y, ystar, sigma2star));
    return __result;
END_RCPP
}
// get_derivative_cpp
double get_derivative_cpp(NumericVector ys, double ystar, double sigma2star, int order);
RcppExport SEXP bayeshscore_get_derivative_cpp(SEXP ysSEXP, SEXP ystarSEXP, SEXP sigma2starSEXP, SEXP orderSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type ys(ysSEXP);
    Rcpp::traits::input_parameter< double >::type ystar(ystarSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2star(sigma2starSEXP);
    Rcpp::traits::input_parameter< int >::type order(orderSEXP);
    __result = Rcpp::wrap(get_derivative_cpp(ys, ystar, sigma2star, order));
    return __result;
END_RCPP
}
// KF_assimilate_one_cpp
List KF_assimilate_one_cpp(NumericVector Yt, int t, NumericVector initial_mean, NumericMatrix initial_var, NumericMatrix phi, NumericMatrix psi, NumericMatrix sigmaV2, NumericMatrix sigmaW2, List KF_current);
RcppExport SEXP bayeshscore_KF_assimilate_one_cpp(SEXP YtSEXP, SEXP tSEXP, SEXP initial_meanSEXP, SEXP initial_varSEXP, SEXP phiSEXP, SEXP psiSEXP, SEXP sigmaV2SEXP, SEXP sigmaW2SEXP, SEXP KF_currentSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type Yt(YtSEXP);
    Rcpp::traits::input_parameter< int >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type initial_mean(initial_meanSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type initial_var(initial_varSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type psi(psiSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type sigmaV2(sigmaV2SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type sigmaW2(sigmaW2SEXP);
    Rcpp::traits::input_parameter< List >::type KF_current(KF_currentSEXP);
    __result = Rcpp::wrap(KF_assimilate_one_cpp(Yt, t, initial_mean, initial_var, phi, psi, sigmaV2, sigmaW2, KF_current));
    return __result;
END_RCPP
}
// KF_filtering_cpp
List KF_filtering_cpp(NumericMatrix Y, NumericVector initial_mean, NumericMatrix initial_var, NumericMatrix phi, NumericMatrix psi, NumericMatrix sigmaV2, NumericMatrix sigmaW2);
RcppExport SEXP bayeshscore_KF_filtering_cpp(SEXP YSEXP, SEXP initial_meanSEXP, SEXP initial_varSEXP, SEXP phiSEXP, SEXP psiSEXP, SEXP sigmaV2SEXP, SEXP sigmaW2SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type Y(YSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type initial_mean(initial_meanSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type initial_var(initial_varSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type psi(psiSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type sigmaV2(sigmaV2SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type sigmaW2(sigmaW2SEXP);
    __result = Rcpp::wrap(KF_filtering_cpp(Y, initial_mean, initial_var, phi, psi, sigmaV2, sigmaW2));
    return __result;
END_RCPP
}
// rtransition_logistic_cpp
NumericMatrix rtransition_logistic_cpp(const NumericMatrix& Xold, const double& delta_t, const double& dt, const double& sigma, const double& r, const double& b);
RcppExport SEXP bayeshscore_rtransition_logistic_cpp(SEXP XoldSEXP, SEXP delta_tSEXP, SEXP dtSEXP, SEXP sigmaSEXP, SEXP rSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type Xold(XoldSEXP);
    Rcpp::traits::input_parameter< const double& >::type delta_t(delta_tSEXP);
    Rcpp::traits::input_parameter< const double& >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< const double& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const double& >::type r(rSEXP);
    Rcpp::traits::input_parameter< const double& >::type b(bSEXP);
    __result = Rcpp::wrap(rtransition_logistic_cpp(Xold, delta_t, dt, sigma, r, b));
    return __result;
END_RCPP
}
// rinitial_SVLevy_cpp
NumericMatrix rinitial_SVLevy_cpp(int N, double t, double xi, double w2, double lambda);
RcppExport SEXP bayeshscore_rinitial_SVLevy_cpp(SEXP NSEXP, SEXP tSEXP, SEXP xiSEXP, SEXP w2SEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< double >::type w2(w2SEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    __result = Rcpp::wrap(rinitial_SVLevy_cpp(N, t, xi, w2, lambda));
    return __result;
END_RCPP
}
// rtransition_SVLevy_cpp
NumericMatrix rtransition_SVLevy_cpp(NumericMatrix Xold, double t_1, double t, double xi, double w2, double lambda);
RcppExport SEXP bayeshscore_rtransition_SVLevy_cpp(SEXP XoldSEXP, SEXP t_1SEXP, SEXP tSEXP, SEXP xiSEXP, SEXP w2SEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type Xold(XoldSEXP);
    Rcpp::traits::input_parameter< double >::type t_1(t_1SEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< double >::type w2(w2SEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    __result = Rcpp::wrap(rtransition_SVLevy_cpp(Xold, t_1, t, xi, w2, lambda));
    return __result;
END_RCPP
}
// dobs_SVLevy_cpp
NumericMatrix dobs_SVLevy_cpp(NumericVector Yt, NumericMatrix Xts, double mu, double beta, bool log);
RcppExport SEXP bayeshscore_dobs_SVLevy_cpp(SEXP YtSEXP, SEXP XtsSEXP, SEXP muSEXP, SEXP betaSEXP, SEXP logSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type Yt(YtSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Xts(XtsSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< bool >::type log(logSEXP);
    __result = Rcpp::wrap(dobs_SVLevy_cpp(Yt, Xts, mu, beta, log));
    return __result;
END_RCPP
}
// d1logdobs_SVLevy_cpp
NumericMatrix d1logdobs_SVLevy_cpp(NumericVector Yt, NumericMatrix Xts, double mu, double beta);
RcppExport SEXP bayeshscore_d1logdobs_SVLevy_cpp(SEXP YtSEXP, SEXP XtsSEXP, SEXP muSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type Yt(YtSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Xts(XtsSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    __result = Rcpp::wrap(d1logdobs_SVLevy_cpp(Yt, Xts, mu, beta));
    return __result;
END_RCPP
}
// d2logdobs_SVLevy_cpp
NumericMatrix d2logdobs_SVLevy_cpp(NumericVector Yt, NumericMatrix Xts, double mu, double beta);
RcppExport SEXP bayeshscore_d2logdobs_SVLevy_cpp(SEXP YtSEXP, SEXP XtsSEXP, SEXP muSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type Yt(YtSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Xts(XtsSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    __result = Rcpp::wrap(d2logdobs_SVLevy_cpp(Yt, Xts, mu, beta));
    return __result;
END_RCPP
}
// rinitial_SVLevy_multifactor_cpp
NumericMatrix rinitial_SVLevy_multifactor_cpp(int N, double t, double xi, double w2, double lambda1, double lambda2, double w);
RcppExport SEXP bayeshscore_rinitial_SVLevy_multifactor_cpp(SEXP NSEXP, SEXP tSEXP, SEXP xiSEXP, SEXP w2SEXP, SEXP lambda1SEXP, SEXP lambda2SEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< double >::type w2(w2SEXP);
    Rcpp::traits::input_parameter< double >::type lambda1(lambda1SEXP);
    Rcpp::traits::input_parameter< double >::type lambda2(lambda2SEXP);
    Rcpp::traits::input_parameter< double >::type w(wSEXP);
    __result = Rcpp::wrap(rinitial_SVLevy_multifactor_cpp(N, t, xi, w2, lambda1, lambda2, w));
    return __result;
END_RCPP
}
// rtransition_SVLevy_multifactor_cpp
NumericMatrix rtransition_SVLevy_multifactor_cpp(NumericMatrix Xold, double t_1, double t, double xi, double w2, double lambda1, double lambda2, double w);
RcppExport SEXP bayeshscore_rtransition_SVLevy_multifactor_cpp(SEXP XoldSEXP, SEXP t_1SEXP, SEXP tSEXP, SEXP xiSEXP, SEXP w2SEXP, SEXP lambda1SEXP, SEXP lambda2SEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type Xold(XoldSEXP);
    Rcpp::traits::input_parameter< double >::type t_1(t_1SEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< double >::type w2(w2SEXP);
    Rcpp::traits::input_parameter< double >::type lambda1(lambda1SEXP);
    Rcpp::traits::input_parameter< double >::type lambda2(lambda2SEXP);
    Rcpp::traits::input_parameter< double >::type w(wSEXP);
    __result = Rcpp::wrap(rtransition_SVLevy_multifactor_cpp(Xold, t_1, t, xi, w2, lambda1, lambda2, w));
    return __result;
END_RCPP
}
// dobs_SVLevy_multifactor_cpp
NumericMatrix dobs_SVLevy_multifactor_cpp(NumericVector Yt, NumericMatrix Xts, double mu, double beta, bool log);
RcppExport SEXP bayeshscore_dobs_SVLevy_multifactor_cpp(SEXP YtSEXP, SEXP XtsSEXP, SEXP muSEXP, SEXP betaSEXP, SEXP logSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type Yt(YtSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Xts(XtsSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< bool >::type log(logSEXP);
    __result = Rcpp::wrap(dobs_SVLevy_multifactor_cpp(Yt, Xts, mu, beta, log));
    return __result;
END_RCPP
}
// d1logdobs_SVLevy_multifactor_cpp
NumericMatrix d1logdobs_SVLevy_multifactor_cpp(NumericVector Yt, NumericMatrix Xts, double mu, double beta);
RcppExport SEXP bayeshscore_d1logdobs_SVLevy_multifactor_cpp(SEXP YtSEXP, SEXP XtsSEXP, SEXP muSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type Yt(YtSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Xts(XtsSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    __result = Rcpp::wrap(d1logdobs_SVLevy_multifactor_cpp(Yt, Xts, mu, beta));
    return __result;
END_RCPP
}
// d2logdobs_SVLevy_multifactor_cpp
NumericMatrix d2logdobs_SVLevy_multifactor_cpp(NumericVector Yt, NumericMatrix Xts, double mu, double beta);
RcppExport SEXP bayeshscore_d2logdobs_SVLevy_multifactor_cpp(SEXP YtSEXP, SEXP XtsSEXP, SEXP muSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type Yt(YtSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Xts(XtsSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    __result = Rcpp::wrap(d2logdobs_SVLevy_multifactor_cpp(Yt, Xts, mu, beta));
    return __result;
END_RCPP
}
// rinitial_SVLevy_multifactorleverage_cpp
NumericMatrix rinitial_SVLevy_multifactorleverage_cpp(int N, double t, double xi, double w2, double lambda1, double lambda2, double w);
RcppExport SEXP bayeshscore_rinitial_SVLevy_multifactorleverage_cpp(SEXP NSEXP, SEXP tSEXP, SEXP xiSEXP, SEXP w2SEXP, SEXP lambda1SEXP, SEXP lambda2SEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< double >::type w2(w2SEXP);
    Rcpp::traits::input_parameter< double >::type lambda1(lambda1SEXP);
    Rcpp::traits::input_parameter< double >::type lambda2(lambda2SEXP);
    Rcpp::traits::input_parameter< double >::type w(wSEXP);
    __result = Rcpp::wrap(rinitial_SVLevy_multifactorleverage_cpp(N, t, xi, w2, lambda1, lambda2, w));
    return __result;
END_RCPP
}
// rtransition_SVLevy_multifactorleverage_cpp
NumericMatrix rtransition_SVLevy_multifactorleverage_cpp(NumericMatrix Xold, double t_1, double t, double xi, double w2, double lambda1, double lambda2, double w);
RcppExport SEXP bayeshscore_rtransition_SVLevy_multifactorleverage_cpp(SEXP XoldSEXP, SEXP t_1SEXP, SEXP tSEXP, SEXP xiSEXP, SEXP w2SEXP, SEXP lambda1SEXP, SEXP lambda2SEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type Xold(XoldSEXP);
    Rcpp::traits::input_parameter< double >::type t_1(t_1SEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< double >::type w2(w2SEXP);
    Rcpp::traits::input_parameter< double >::type lambda1(lambda1SEXP);
    Rcpp::traits::input_parameter< double >::type lambda2(lambda2SEXP);
    Rcpp::traits::input_parameter< double >::type w(wSEXP);
    __result = Rcpp::wrap(rtransition_SVLevy_multifactorleverage_cpp(Xold, t_1, t, xi, w2, lambda1, lambda2, w));
    return __result;
END_RCPP
}
// dobs_SVLevy_multifactorleverage_cpp
NumericMatrix dobs_SVLevy_multifactorleverage_cpp(NumericVector Yt, NumericMatrix Xts, double mu, double beta, double xi, double lambda1, double lambda2, double w, double rho1, double rho2, bool log);
RcppExport SEXP bayeshscore_dobs_SVLevy_multifactorleverage_cpp(SEXP YtSEXP, SEXP XtsSEXP, SEXP muSEXP, SEXP betaSEXP, SEXP xiSEXP, SEXP lambda1SEXP, SEXP lambda2SEXP, SEXP wSEXP, SEXP rho1SEXP, SEXP rho2SEXP, SEXP logSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type Yt(YtSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Xts(XtsSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< double >::type lambda1(lambda1SEXP);
    Rcpp::traits::input_parameter< double >::type lambda2(lambda2SEXP);
    Rcpp::traits::input_parameter< double >::type w(wSEXP);
    Rcpp::traits::input_parameter< double >::type rho1(rho1SEXP);
    Rcpp::traits::input_parameter< double >::type rho2(rho2SEXP);
    Rcpp::traits::input_parameter< bool >::type log(logSEXP);
    __result = Rcpp::wrap(dobs_SVLevy_multifactorleverage_cpp(Yt, Xts, mu, beta, xi, lambda1, lambda2, w, rho1, rho2, log));
    return __result;
END_RCPP
}
// d1logdobs_SVLevy_multifactorleverage_cpp
NumericMatrix d1logdobs_SVLevy_multifactorleverage_cpp(NumericVector Yt, NumericMatrix Xts, double mu, double beta, double xi, double lambda1, double lambda2, double w, double rho1, double rho2);
RcppExport SEXP bayeshscore_d1logdobs_SVLevy_multifactorleverage_cpp(SEXP YtSEXP, SEXP XtsSEXP, SEXP muSEXP, SEXP betaSEXP, SEXP xiSEXP, SEXP lambda1SEXP, SEXP lambda2SEXP, SEXP wSEXP, SEXP rho1SEXP, SEXP rho2SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type Yt(YtSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Xts(XtsSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< double >::type lambda1(lambda1SEXP);
    Rcpp::traits::input_parameter< double >::type lambda2(lambda2SEXP);
    Rcpp::traits::input_parameter< double >::type w(wSEXP);
    Rcpp::traits::input_parameter< double >::type rho1(rho1SEXP);
    Rcpp::traits::input_parameter< double >::type rho2(rho2SEXP);
    __result = Rcpp::wrap(d1logdobs_SVLevy_multifactorleverage_cpp(Yt, Xts, mu, beta, xi, lambda1, lambda2, w, rho1, rho2));
    return __result;
END_RCPP
}
// d2logdobs_SVLevy_multifactorleverage_cpp
NumericMatrix d2logdobs_SVLevy_multifactorleverage_cpp(NumericVector Yt, NumericMatrix Xts, double mu, double beta);
RcppExport SEXP bayeshscore_d2logdobs_SVLevy_multifactorleverage_cpp(SEXP YtSEXP, SEXP XtsSEXP, SEXP muSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type Yt(YtSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Xts(XtsSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    __result = Rcpp::wrap(d2logdobs_SVLevy_multifactorleverage_cpp(Yt, Xts, mu, beta));
    return __result;
END_RCPP
}
