# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

multinomial_resampling_n_ <- function(weights, ndraws) {
    .Call('HyvarinenSSM_multinomial_resampling_n_', PACKAGE = 'HyvarinenSSM', weights, ndraws)
}

rmvnorm <- function(nsamples, mean, covariance) {
    .Call('HyvarinenSSM_rmvnorm', PACKAGE = 'HyvarinenSSM', nsamples, mean, covariance)
}

rmvnorm_transpose <- function(nsamples, mean, covariance) {
    .Call('HyvarinenSSM_rmvnorm_transpose', PACKAGE = 'HyvarinenSSM', nsamples, mean, covariance)
}

dmvnorm <- function(x, mean, covariance) {
    .Call('HyvarinenSSM_dmvnorm', PACKAGE = 'HyvarinenSSM', x, mean, covariance)
}

dmvnorm_transpose <- function(x, mean, covariance) {
    .Call('HyvarinenSSM_dmvnorm_transpose', PACKAGE = 'HyvarinenSSM', x, mean, covariance)
}

systematic_resampling_n_ <- function(weights, ndraws, u) {
    .Call('HyvarinenSSM_systematic_resampling_n_', PACKAGE = 'HyvarinenSSM', weights, ndraws, u)
}

phi_cpp <- function(y, yi, sigma2) {
    .Call('HyvarinenSSM_phi_cpp', PACKAGE = 'HyvarinenSSM', y, yi, sigma2)
}

dphi_cpp <- function(y, yi, sigma2) {
    .Call('HyvarinenSSM_dphi_cpp', PACKAGE = 'HyvarinenSSM', y, yi, sigma2)
}

d2phi_cpp <- function(y, yi, sigma2) {
    .Call('HyvarinenSSM_d2phi_cpp', PACKAGE = 'HyvarinenSSM', y, yi, sigma2)
}

get_G_RBF_cpp <- function(x, sigma2) {
    .Call('HyvarinenSSM_get_G_RBF_cpp', PACKAGE = 'HyvarinenSSM', x, sigma2)
}

get_h1_RBF_cpp <- function(x, sigma2) {
    .Call('HyvarinenSSM_get_h1_RBF_cpp', PACKAGE = 'HyvarinenSSM', x, sigma2)
}

get_h2_RBF_cpp <- function(x, sigma2) {
    .Call('HyvarinenSSM_get_h2_RBF_cpp', PACKAGE = 'HyvarinenSSM', x, sigma2)
}

loss_d1 <- function(theta, sigma2, Gtraining, xtraining, xtest) {
    .Call('HyvarinenSSM_loss_d1', PACKAGE = 'HyvarinenSSM', theta, sigma2, Gtraining, xtraining, xtest)
}

loss_d2 <- function(theta, sigma2, Gtraining, xtraining, xtest) {
    .Call('HyvarinenSSM_loss_d2', PACKAGE = 'HyvarinenSSM', theta, sigma2, Gtraining, xtraining, xtest)
}

K_cpp <- function(y, ystar, sigma2star) {
    .Call('HyvarinenSSM_K_cpp', PACKAGE = 'HyvarinenSSM', y, ystar, sigma2star)
}

dK_cpp <- function(y, ystar, sigma2star) {
    .Call('HyvarinenSSM_dK_cpp', PACKAGE = 'HyvarinenSSM', y, ystar, sigma2star)
}

d2K_cpp <- function(y, ystar, sigma2star) {
    .Call('HyvarinenSSM_d2K_cpp', PACKAGE = 'HyvarinenSSM', y, ystar, sigma2star)
}

get_derivative_cpp <- function(ys, ystar, sigma2star, order) {
    .Call('HyvarinenSSM_get_derivative_cpp', PACKAGE = 'HyvarinenSSM', ys, ystar, sigma2star, order)
}

KF_assimilate_one_cpp <- function(Yt, t, initial_mean, initial_var, phi, psi, sigmaV2, sigmaW2, KF_current) {
    .Call('HyvarinenSSM_KF_assimilate_one_cpp', PACKAGE = 'HyvarinenSSM', Yt, t, initial_mean, initial_var, phi, psi, sigmaV2, sigmaW2, KF_current)
}

KF_filtering_cpp <- function(Y, initial_mean, initial_var, phi, psi, sigmaV2, sigmaW2) {
    .Call('HyvarinenSSM_KF_filtering_cpp', PACKAGE = 'HyvarinenSSM', Y, initial_mean, initial_var, phi, psi, sigmaV2, sigmaW2)
}

rtransition_logistic_cpp <- function(Xold, delta_t, dt, sigma, r, b) {
    .Call('HyvarinenSSM_rtransition_logistic_cpp', PACKAGE = 'HyvarinenSSM', Xold, delta_t, dt, sigma, r, b)
}

rinitial_SVLevy_cpp <- function(N, t, xi, w2, lambda) {
    .Call('HyvarinenSSM_rinitial_SVLevy_cpp', PACKAGE = 'HyvarinenSSM', N, t, xi, w2, lambda)
}

rtransition_SVLevy_cpp <- function(Xold, t_1, t, xi, w2, lambda) {
    .Call('HyvarinenSSM_rtransition_SVLevy_cpp', PACKAGE = 'HyvarinenSSM', Xold, t_1, t, xi, w2, lambda)
}

dobs_SVLevy_cpp <- function(Yt, Xts, mu, beta, log) {
    .Call('HyvarinenSSM_dobs_SVLevy_cpp', PACKAGE = 'HyvarinenSSM', Yt, Xts, mu, beta, log)
}

d1logdobs_SVLevy_cpp <- function(Yt, Xts, mu, beta) {
    .Call('HyvarinenSSM_d1logdobs_SVLevy_cpp', PACKAGE = 'HyvarinenSSM', Yt, Xts, mu, beta)
}

d2logdobs_SVLevy_cpp <- function(Yt, Xts, mu, beta) {
    .Call('HyvarinenSSM_d2logdobs_SVLevy_cpp', PACKAGE = 'HyvarinenSSM', Yt, Xts, mu, beta)
}

rinitial_SVLevy_multifactor_cpp <- function(N, t, xi, w2, lambda1, lambda2, w) {
    .Call('HyvarinenSSM_rinitial_SVLevy_multifactor_cpp', PACKAGE = 'HyvarinenSSM', N, t, xi, w2, lambda1, lambda2, w)
}

rtransition_SVLevy_multifactor_cpp <- function(Xold, t_1, t, xi, w2, lambda1, lambda2, w) {
    .Call('HyvarinenSSM_rtransition_SVLevy_multifactor_cpp', PACKAGE = 'HyvarinenSSM', Xold, t_1, t, xi, w2, lambda1, lambda2, w)
}

dobs_SVLevy_multifactor_cpp <- function(Yt, Xts, mu, beta, log) {
    .Call('HyvarinenSSM_dobs_SVLevy_multifactor_cpp', PACKAGE = 'HyvarinenSSM', Yt, Xts, mu, beta, log)
}

d1logdobs_SVLevy_multifactor_cpp <- function(Yt, Xts, mu, beta) {
    .Call('HyvarinenSSM_d1logdobs_SVLevy_multifactor_cpp', PACKAGE = 'HyvarinenSSM', Yt, Xts, mu, beta)
}

d2logdobs_SVLevy_multifactor_cpp <- function(Yt, Xts, mu, beta) {
    .Call('HyvarinenSSM_d2logdobs_SVLevy_multifactor_cpp', PACKAGE = 'HyvarinenSSM', Yt, Xts, mu, beta)
}

rinitial_SVLevy_multifactorleverage_cpp <- function(N, t, xi, w2, lambda1, lambda2, w) {
    .Call('HyvarinenSSM_rinitial_SVLevy_multifactorleverage_cpp', PACKAGE = 'HyvarinenSSM', N, t, xi, w2, lambda1, lambda2, w)
}

rtransition_SVLevy_multifactorleverage_cpp <- function(Xold, t_1, t, xi, w2, lambda1, lambda2, w) {
    .Call('HyvarinenSSM_rtransition_SVLevy_multifactorleverage_cpp', PACKAGE = 'HyvarinenSSM', Xold, t_1, t, xi, w2, lambda1, lambda2, w)
}

dobs_SVLevy_multifactorleverage_cpp <- function(Yt, Xts, mu, beta, xi, lambda1, lambda2, w, rho1, rho2, log) {
    .Call('HyvarinenSSM_dobs_SVLevy_multifactorleverage_cpp', PACKAGE = 'HyvarinenSSM', Yt, Xts, mu, beta, xi, lambda1, lambda2, w, rho1, rho2, log)
}

d1logdobs_SVLevy_multifactorleverage_cpp <- function(Yt, Xts, mu, beta, xi, lambda1, lambda2, w, rho1, rho2) {
    .Call('HyvarinenSSM_d1logdobs_SVLevy_multifactorleverage_cpp', PACKAGE = 'HyvarinenSSM', Yt, Xts, mu, beta, xi, lambda1, lambda2, w, rho1, rho2)
}

d2logdobs_SVLevy_multifactorleverage_cpp <- function(Yt, Xts, mu, beta) {
    .Call('HyvarinenSSM_d2logdobs_SVLevy_multifactorleverage_cpp', PACKAGE = 'HyvarinenSSM', Yt, Xts, mu, beta)
}

