# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

multinomial_resampling_n_ <- function(weights, ndraws) {
    .Call('HyvarinenSSM_multinomial_resampling_n_', PACKAGE = 'HyvarinenSSM', weights, ndraws)
}

rmvnorm <- function(nsamples, mean, covariance) {
    .Call('HyvarinenSSM_rmvnorm', PACKAGE = 'HyvarinenSSM', nsamples, mean, covariance)
}

rmvnorm_transpose <- function(nsamples, mean, covariance) {
    .Call('HyvarinenSSM_rmvnorm_transpose', PACKAGE = 'HyvarinenSSM', nsamples, mean, covariance)
}

rmvnorm_transpose_cholesky <- function(nsamples, mean, cholesky_covariance) {
    .Call('HyvarinenSSM_rmvnorm_transpose_cholesky', PACKAGE = 'HyvarinenSSM', nsamples, mean, cholesky_covariance)
}

dmvnorm <- function(x, mean, covariance) {
    .Call('HyvarinenSSM_dmvnorm', PACKAGE = 'HyvarinenSSM', x, mean, covariance)
}

dmvnorm_transpose <- function(x, mean, covariance) {
    .Call('HyvarinenSSM_dmvnorm_transpose', PACKAGE = 'HyvarinenSSM', x, mean, covariance)
}

dmvnorm_transpose_cholesky <- function(x, mean, cholesky_covariance) {
    .Call('HyvarinenSSM_dmvnorm_transpose_cholesky', PACKAGE = 'HyvarinenSSM', x, mean, cholesky_covariance)
}

rtransition_logistic_c <- function(Xt, dt, sigma, r, b) {
    .Call('HyvarinenSSM_rtransition_logistic_c', PACKAGE = 'HyvarinenSSM', Xt, dt, sigma, r, b)
}

systematic_resampling_n_ <- function(weights, ndraws, u) {
    .Call('HyvarinenSSM_systematic_resampling_n_', PACKAGE = 'HyvarinenSSM', weights, ndraws, u)
}

