# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

multinomial_resampling_n_ <- function(weights, ndraws) {
    .Call('_bayeshscore_multinomial_resampling_n_', PACKAGE = 'bayeshscore', weights, ndraws)
}

rmvnorm <- function(nsamples, mean, covariance) {
    .Call('_bayeshscore_rmvnorm', PACKAGE = 'bayeshscore', nsamples, mean, covariance)
}

rmvnorm_transpose <- function(nsamples, mean, covariance) {
    .Call('_bayeshscore_rmvnorm_transpose', PACKAGE = 'bayeshscore', nsamples, mean, covariance)
}

dmvnorm <- function(x, mean, covariance) {
    .Call('_bayeshscore_dmvnorm', PACKAGE = 'bayeshscore', x, mean, covariance)
}

dmvnorm_transpose <- function(x, mean, covariance) {
    .Call('_bayeshscore_dmvnorm_transpose', PACKAGE = 'bayeshscore', x, mean, covariance)
}

SSP_resampling_n_ <- function(weights, u, tol = 1e-15) {
    .Call('_bayeshscore_SSP_resampling_n_', PACKAGE = 'bayeshscore', weights, u, tol)
}

systematic_resampling_n_ <- function(weights, ndraws, u) {
    .Call('_bayeshscore_systematic_resampling_n_', PACKAGE = 'bayeshscore', weights, ndraws, u)
}

phi_cpp <- function(y, yi, sigma2) {
    .Call('_bayeshscore_phi_cpp', PACKAGE = 'bayeshscore', y, yi, sigma2)
}

dphi_cpp <- function(y, yi, sigma2) {
    .Call('_bayeshscore_dphi_cpp', PACKAGE = 'bayeshscore', y, yi, sigma2)
}

d2phi_cpp <- function(y, yi, sigma2) {
    .Call('_bayeshscore_d2phi_cpp', PACKAGE = 'bayeshscore', y, yi, sigma2)
}

get_G_RBF_cpp <- function(x, sigma2) {
    .Call('_bayeshscore_get_G_RBF_cpp', PACKAGE = 'bayeshscore', x, sigma2)
}

get_h1_RBF_cpp <- function(x, sigma2) {
    .Call('_bayeshscore_get_h1_RBF_cpp', PACKAGE = 'bayeshscore', x, sigma2)
}

get_h2_RBF_cpp <- function(x, sigma2) {
    .Call('_bayeshscore_get_h2_RBF_cpp', PACKAGE = 'bayeshscore', x, sigma2)
}

loss_d1 <- function(theta, sigma2, Gtraining, xtraining, xtest) {
    .Call('_bayeshscore_loss_d1', PACKAGE = 'bayeshscore', theta, sigma2, Gtraining, xtraining, xtest)
}

loss_d2 <- function(theta, sigma2, Gtraining, xtraining, xtest) {
    .Call('_bayeshscore_loss_d2', PACKAGE = 'bayeshscore', theta, sigma2, Gtraining, xtraining, xtest)
}

K_cpp <- function(y, ystar, sigma2star) {
    .Call('_bayeshscore_K_cpp', PACKAGE = 'bayeshscore', y, ystar, sigma2star)
}

dK_cpp <- function(y, ystar, sigma2star) {
    .Call('_bayeshscore_dK_cpp', PACKAGE = 'bayeshscore', y, ystar, sigma2star)
}

d2K_cpp <- function(y, ystar, sigma2star) {
    .Call('_bayeshscore_d2K_cpp', PACKAGE = 'bayeshscore', y, ystar, sigma2star)
}

get_derivative_cpp <- function(ys, ystar, sigma2star, order) {
    .Call('_bayeshscore_get_derivative_cpp', PACKAGE = 'bayeshscore', ys, ystar, sigma2star, order)
}

KF_assimilate_one_cpp <- function(Yt, t, initial_mean, initial_var, phi, psi, sigmaV2, sigmaW2, KF_current) {
    .Call('_bayeshscore_KF_assimilate_one_cpp', PACKAGE = 'bayeshscore', Yt, t, initial_mean, initial_var, phi, psi, sigmaV2, sigmaW2, KF_current)
}

KF_filtering_cpp <- function(Y, initial_mean, initial_var, phi, psi, sigmaV2, sigmaW2) {
    .Call('_bayeshscore_KF_filtering_cpp', PACKAGE = 'bayeshscore', Y, initial_mean, initial_var, phi, psi, sigmaV2, sigmaW2)
}

rtransition_logistic_cpp <- function(Xold, delta_t, dt, sigma, r, b) {
    .Call('_bayeshscore_rtransition_logistic_cpp', PACKAGE = 'bayeshscore', Xold, delta_t, dt, sigma, r, b)
}

rinitial_SVLevy_cpp <- function(N, t, xi, w2, lambda) {
    .Call('_bayeshscore_rinitial_SVLevy_cpp', PACKAGE = 'bayeshscore', N, t, xi, w2, lambda)
}

rtransition_SVLevy_cpp <- function(Xold, t_1, t, xi, w2, lambda) {
    .Call('_bayeshscore_rtransition_SVLevy_cpp', PACKAGE = 'bayeshscore', Xold, t_1, t, xi, w2, lambda)
}

dobs_SVLevy_cpp <- function(Yt, Xts, mu, beta, log) {
    .Call('_bayeshscore_dobs_SVLevy_cpp', PACKAGE = 'bayeshscore', Yt, Xts, mu, beta, log)
}

d1logdobs_SVLevy_cpp <- function(Yt, Xts, mu, beta) {
    .Call('_bayeshscore_d1logdobs_SVLevy_cpp', PACKAGE = 'bayeshscore', Yt, Xts, mu, beta)
}

d2logdobs_SVLevy_cpp <- function(Yt, Xts, mu, beta) {
    .Call('_bayeshscore_d2logdobs_SVLevy_cpp', PACKAGE = 'bayeshscore', Yt, Xts, mu, beta)
}

rinitial_SVLevy_multifactor_cpp <- function(N, t, xi, w2, lambda1, lambda2, w) {
    .Call('_bayeshscore_rinitial_SVLevy_multifactor_cpp', PACKAGE = 'bayeshscore', N, t, xi, w2, lambda1, lambda2, w)
}

rtransition_SVLevy_multifactor_cpp <- function(Xold, t_1, t, xi, w2, lambda1, lambda2, w) {
    .Call('_bayeshscore_rtransition_SVLevy_multifactor_cpp', PACKAGE = 'bayeshscore', Xold, t_1, t, xi, w2, lambda1, lambda2, w)
}

dobs_SVLevy_multifactor_cpp <- function(Yt, Xts, mu, beta, log) {
    .Call('_bayeshscore_dobs_SVLevy_multifactor_cpp', PACKAGE = 'bayeshscore', Yt, Xts, mu, beta, log)
}

d1logdobs_SVLevy_multifactor_cpp <- function(Yt, Xts, mu, beta) {
    .Call('_bayeshscore_d1logdobs_SVLevy_multifactor_cpp', PACKAGE = 'bayeshscore', Yt, Xts, mu, beta)
}

d2logdobs_SVLevy_multifactor_cpp <- function(Yt, Xts, mu, beta) {
    .Call('_bayeshscore_d2logdobs_SVLevy_multifactor_cpp', PACKAGE = 'bayeshscore', Yt, Xts, mu, beta)
}

rinitial_SVLevy_multifactorleverage_cpp <- function(N, t, xi, w2, lambda1, lambda2, w) {
    .Call('_bayeshscore_rinitial_SVLevy_multifactorleverage_cpp', PACKAGE = 'bayeshscore', N, t, xi, w2, lambda1, lambda2, w)
}

rtransition_SVLevy_multifactorleverage_cpp <- function(Xold, t_1, t, xi, w2, lambda1, lambda2, w) {
    .Call('_bayeshscore_rtransition_SVLevy_multifactorleverage_cpp', PACKAGE = 'bayeshscore', Xold, t_1, t, xi, w2, lambda1, lambda2, w)
}

dobs_SVLevy_multifactorleverage_cpp <- function(Yt, Xts, mu, beta, xi, lambda1, lambda2, w, rho1, rho2, log) {
    .Call('_bayeshscore_dobs_SVLevy_multifactorleverage_cpp', PACKAGE = 'bayeshscore', Yt, Xts, mu, beta, xi, lambda1, lambda2, w, rho1, rho2, log)
}

d1logdobs_SVLevy_multifactorleverage_cpp <- function(Yt, Xts, mu, beta, xi, lambda1, lambda2, w, rho1, rho2) {
    .Call('_bayeshscore_d1logdobs_SVLevy_multifactorleverage_cpp', PACKAGE = 'bayeshscore', Yt, Xts, mu, beta, xi, lambda1, lambda2, w, rho1, rho2)
}

d2logdobs_SVLevy_multifactorleverage_cpp <- function(Yt, Xts, mu, beta) {
    .Call('_bayeshscore_d2logdobs_SVLevy_multifactorleverage_cpp', PACKAGE = 'bayeshscore', Yt, Xts, mu, beta)
}

